spring:
  application:
    name: tenantflow-api

  datasource:
    url: jdbc:postgresql://localhost:5432/tenantflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        tenant_identifier_resolver: org.example.config.multitenancy.TenantIdentifierResolver
        multi_tenant_connection_provider: org.example.config.multitenancy.TenantConnectionProvider

  flyway:
    enabled: false

server:
  port: 8081